name: Build and Deploy
on:
  push:
    branches:
      - main  # replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Build ğŸ—ï¸
        run: bash ./path_to_your_script.sh  # replace with your bash script path

      - name: Deploy ğŸš€
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.yourdomain.com  # replace with your server
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/your_project  # replace with your server directory
