name: "Maintenance: Build Debian"
#
# Description
#

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  Debian:
    uses: armbian/scripts/.github/workflows/pack-debian.yml@main
    with:
      matrix: "all:jammy"
      maintainer: "Igor Pecovnik <igor@armbian.com>"
      package: "armbian-config"
      licence: "GPL 2.0"
      homepage: "https://www.armbian.com"
      section: "default"
      priority: "optional"
      compile: "tools/config-assemble.sh -p"
      depends: "bash, jq, whiptail, sudo, procps, systemd, lsb-release, iproute2, debconf, libtext-iconv-perl, gpg, xz-utils, pv"
      description: "Armbian config: The Next Generation"

    secrets:
      PRIMARY_KEY: ${{ secrets.GPG_KEY4 }}
      TERTIARY_KEY: ${{ secrets.GPG_KEY3 }}

  Tests:
    name: "Execute unit tests"
    if: ${{ github.repository_owner == 'Armbian' }}
    needs: Debian
    runs-on: ubuntu-latest
    steps:

      - name: "Run unit tests action"
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: "Unit tests"
